# Generated by Django 5.2.1 on 2025-08-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0003_bookmodel_delete_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_model',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
