# Generated by Django 5.2.1 on 2025-08-17 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0006_borrowmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowmodel',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
