# Generated by Django 5.2.1 on 2025-08-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0007_alter_borrowmodel_returned_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='media_file'),
        ),
    ]
