# Generated by Django 5.2.1 on 2025-08-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmodel',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('BORROW', 'Borrow'), ('RETURN', 'Return')], default='DEPOSIT', editable=False, max_length=15),
        ),
    ]
